name: cli
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  ansi: ^0.4.2
  args: ^2.5.0
  http: ^1.2.1
  image: ^4.1.7
  mime: ^1.0.5
  path: ^1.9.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.4

dependency_overrides:
  pointycastle: 3.8.0

executables:
  cli: cli.dart
